# Análise Exploratória de Dados (EDA)

Fazemos a primeira análise sobre os dados coletados na Base do INEP

**Importações**

In [2]:
import pandas as pd
from pathlib import Path

pd.set_option('display.max_columns', None)

##  Informações contidas nos dados de 2024

### `resultados_2024`

In [3]:
caminho_resultados_2024 = Path.cwd().parent / 'data' / 'raw' / '2024' / 'RESULTADOS_2024.csv'

df_resultados_2024 = pd.read_csv(caminho_resultados_2024, encoding="latin-1", sep=";", nrows=1000)

In [4]:
df_resultados_2024.head(10)

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,2301406,Aratuba,23,CE,1,1,1,1,1420.0,1383.0,1395.0,1408.0,436.8,377.8,423.4,427.1,CAABADDBBBACACACDEABDBABDDCCBACDCCBAACCABCBAC,BEABBCDABCDBAEEBDDABCCDAADDABACDDAB..........,BCADBCDCEDBDDBDDCDBCBB*BBDEAEEBCDCABBDDAAECEE,CBDCCADBBECCBADEACCBDCACECDDABBDBADBAAEDBCCAB,1,CAEDAACCAEEXCBBAEDBBCAACDEDCBCEECAAEDDDEBBDDB,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,3604651,2024,42103770.0,4218004.0,Tijucas,42.0,SC,4.0,1.0,1.0,4218004,Tijucas,42,SC,1,1,1,1,1422.0,1384.0,1396.0,1410.0,521.9,601.9,605.5,689.2,EBDEEADAECCAAEDBBEDABACDBCEEDDDEDBDDABDBCCECA,BADBACDAECEDEABBEADDBBDEBEDADEDEEACBBECABCEDA,AACEACADECBCDAEEBEDCBCBEDDCDEAEDEBDABDCECDDDB,DBAEDBECBDDBCCBBABBDECCCCEECBACCDBCDAAABBAAAD,0,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,200.0,180.0,180.0,920.0
2,1461268,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4122404,Rolândia,41,PR,1,1,1,1,1419.0,1385.0,1398.0,1407.0,363.0,548.4,557.2,456.4,CABAECDBADDCDEACABEACEABEDDCEDCDCCBDBDBDDBDCC,DAEDBCDCEBCCECADDACABDEBDCDECEDBEABECBCBBDBCD,BBCABCACDDEECCBCECECADEECCBEADBBEDBDDDEDDEECB,EBADBEDDDBCBCBCDCCECAAADDDECCDBDACACCEAEACDAC,1,BCEAACDEDCAAEDDDEBBDDBECCAEDBBAAACCAEEXCBBCED,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,120.0,120.0,40.0,120.0,80.0,480.0
3,4301058,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3534401,Osasco,35,SP,1,1,1,1,1421.0,1386.0,1397.0,1409.0,550.7,553.8,605.9,629.1,DDAAECECCBDBECBCBEAAADCBDDBBBEDADBDCCEEBCDAAD,ACCEADCEBDEECEDCCAADBBBCBCEABCD*AECAA........,AACEACBEDBAEEBEABDABCECDBACDCDDDCADEDDDECBEDE,BBBCDACDCABADAEACCECBCDAECECECCECBDEDABEDBCBA,0,DDBDDEBBAAEDECBCEEDCAACDBBCEDBBAEXCCAEAACCAED,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,140.0,200.0,160.0,160.0,80.0,740.0
4,3148322,2024,21150354.0,2100436.0,Alto Alegre do Maranhão,21.0,MA,2.0,1.0,1.0,2111508,São Mateus do Maranhão,21,MA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1035588,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2408102,Natal,24,RN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3587454,2024,15585689.0,1501402.0,Belém,15.0,PA,4.0,1.0,1.0,1501402,Belém,15,PA,1,2,2,1,1420.0,NaN,NaN,1408.0,486.7,NaN,NaN,525.1,ECCDAACEAACCBAABCBBDBAECBDBCACBEEDBDDADEADDAC,NaN,NaN,DCBBBBEAACECBBCBBACBCACCBDDCCAAEBBBDBECBDDABC,0,CAEDAACCAEEXCBBAEDBBCAACDEDCBCEECAAEDDDEBBDDB,NaN,NaN,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,140768,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2408102,Natal,24,RN,1,1,1,1,1419.0,1385.0,1398.0,1407.0,482.7,531.6,439.2,496.7,BECBCDCEECCDDEDDAAACCEDBEEEBABBEEBEDEEEDDDDDC,CABEECBCBACCDCAABEDABDEAAEEDEEDBCADECEABCDDCD,BDC*ABDCBCDEEDABECBCBEDEACEDAECECEDDDDDCABDDE,DCCDBEDCCCCADDD*ACBAEBCDCEEECDEDAEBEDDDEBCADC,1,BCEAACDEDCAAEDDDEBBDDBECCAEDBBAAACCAEEXCBBCED,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,100.0,80.0,60.0,120.0,0.0,360.0
8,3541867,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3156700,Sabará,31,MG,0,2,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3371353,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3520509,Indaiatuba,35,SP,1,1,1,1,1420.0,1383.0,1395.0,1408.0,599.5,640.3,597.6,665.3,EAEEADBCAABDCEBAEDACBDECCDBDBCEEBADCEEDEADDDD,CECEBEBEDCCDCEDBABCDCAACEDADEAEAAEADECDEDACBE,CAAAEACBECDDDBBDEDCCECEACBCDAAABDBEBBBEBADEEB,CEAAAEEABBAACCAABCCEAECCCECBCCCCBAADDCBDDBBDD,0,CAEDAACCAEEXCBBAEDBBCAACDEDCBCEECAAEDDDEBBDDB,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,120.0,200.0,120.0,120.0,200.0,760.0

In [5]:

df_resultados_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NU_SEQUENCIAL           1000 non-null   int64
 1   NU_ANO                  1000 non-null   int64
 2   CO_ESCOLA               348 non-null    float64
 3   CO_MUNICIPIO_ESC        348 non-null    float64
 4   NO_MUNICIPIO_ESC        348 non-null    str
 5   CO_UF_ESC               348 non-null    float64
 6   SG_UF_ESC               348 non-null    str
 7   TP_DEPENDENCIA_ADM_ESC  348 non-null    float64
 8   TP_LOCALIZACAO_ESC      348 non-null    float64
 9   TP_SIT_FUNC_ESC         348 non-null    float64
 10  CO_MUNICIPIO_PROVA      1000 non-null   int64
 11  NO_MUNICIPIO_PROVA      1000 non-null   str
 12  CO_UF_PROVA             1000 non-null   int64
 13  SG_UF_PROVA             1000 non-null   str
 14  TP_PRESENCA_CN          1000 non-null   int64
 15  TP_PRESENCA_CH          1000 non-null   int64
 16  TP_PRESENCA_LC          1000 non-null   int64
 17  TP_PRESENCA_MT          1000 non-null   int64
 18  CO_PROVA_CN             675 non-null    float64
 19  CO_PROVA_CH             710 non-null    float64
 20  CO_PROVA_LC             710 non-null    float64
 21  CO_PROVA_MT             675 non-null    float64
 22  NU_NOTA_CN              675 non-null    float64
 23  NU_NOTA_CH              710 non-null    float64
 24  NU_NOTA_LC              710 non-null    float64
 25  NU_NOTA_MT              675 non-null    float64
 26  TX_RESPOSTAS_CN         675 non-null    str
 27  TX_RESPOSTAS_CH         710 non-null    str
 28  TX_RESPOSTAS_LC         710 non-null    str
 29  TX_RESPOSTAS_MT         675 non-null    str
 30  TP_LINGUA               1000 non-null   int64
 31  TX_GABARITO_CN          675 non-null    str
 32  TX_GABARITO_CH          710 non-null    str
 33  TX_GABARITO_LC          710 non-null    str
 34  TX_GABARITO_MT          675 non-null    str
 35  TP_STATUS_REDACAO       710 non-null    float64
 36  NU_NOTA_COMP1           710 non-null    float64
 37  NU_NOTA_COMP2           710 non-null    float64
 38  NU_NOTA_COMP3           710 non-null    float64
 39  NU_NOTA_COMP4           710 non-null    float64
 40  NU_NOTA_COMP5           710 non-null    float64
 41  NU_NOTA_REDACAO         710 non-null    float64
dtypes: float64(21), int64(9), str(12)
memory usage: 328.3 KB

In [6]:
df_resultados_2024.isnull().sum()

NU_SEQUENCIAL               0
NU_ANO                      0
CO_ESCOLA                 652
CO_MUNICIPIO_ESC          652
NO_MUNICIPIO_ESC          652
CO_UF_ESC                 652
SG_UF_ESC                 652
TP_DEPENDENCIA_ADM_ESC    652
TP_LOCALIZACAO_ESC        652
TP_SIT_FUNC_ESC           652
CO_MUNICIPIO_PROVA          0
NO_MUNICIPIO_PROVA          0
CO_UF_PROVA                 0
SG_UF_PROVA                 0
TP_PRESENCA_CN              0
TP_PRESENCA_CH              0
TP_PRESENCA_LC              0
TP_PRESENCA_MT              0
CO_PROVA_CN               325
CO_PROVA_CH               290
CO_PROVA_LC               290
CO_PROVA_MT               325
NU_NOTA_CN                325
NU_NOTA_CH                290
NU_NOTA_LC                290
NU_NOTA_MT                325
TX_RESPOSTAS_CN           325
TX_RESPOSTAS_CH           290
TX_RESPOSTAS_LC           290
TX_RESPOSTAS_MT           325
TP_LINGUA                   0
TX_GABARITO_CN            325
TX_GABARITO_CH            290
TX_GABARITO_LC            290
TX_GABARITO_MT            325
TP_STATUS_REDACAO         290
NU_NOTA_COMP1             290
NU_NOTA_COMP2             290
NU_NOTA_COMP3             290
NU_NOTA_COMP4             290
NU_NOTA_COMP5             290
NU_NOTA_REDACAO           290
dtype: int64

In [ ]:
df_resultados_2024.isnull().sum() [df_resultados_2024.isnull().sum() > 0].sort_values(ascending=False)

CO_ESCOLA                 652
CO_MUNICIPIO_ESC          652
NO_MUNICIPIO_ESC          652
CO_UF_ESC                 652
SG_UF_ESC                 652
TP_DEPENDENCIA_ADM_ESC    652
TP_LOCALIZACAO_ESC        652
TP_SIT_FUNC_ESC           652
CO_PROVA_CN               325
CO_PROVA_CH               290
CO_PROVA_LC               290
CO_PROVA_MT               325
NU_NOTA_CN                325
NU_NOTA_CH                290
NU_NOTA_LC                290
NU_NOTA_MT                325
TX_RESPOSTAS_CN           325
TX_RESPOSTAS_CH           290
TX_RESPOSTAS_LC           290
TX_RESPOSTAS_MT           325
TX_GABARITO_CN            325
TX_GABARITO_CH            290
TX_GABARITO_LC            290
TX_GABARITO_MT            325
TP_STATUS_REDACAO         290
NU_NOTA_COMP1             290
NU_NOTA_COMP2             290
NU_NOTA_COMP3             290
NU_NOTA_COMP4             290
NU_NOTA_COMP5             290
NU_NOTA_REDACAO           290
dtype: int64

### `participantes_2024`

In [8]:
participantes_2024 = Path.cwd().parent / 'data' / 'raw' / '2024' / 'PARTICIPANTES_2024.csv' 

df_participantes_2024 = pd.read_csv(participantes_2024, encoding="latin-1", sep=";", nrows=1000)

In [9]:
df_participantes_2024.head(10)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
0,210062064233,2024,5,F,1,1,1,1,3,NaN,0,4314902,Porto Alegre,43,RS,F,F,C,D,4,B,C,A,C,D,C,B,B,A,B,B,B,D,A,B,B,E,A
1,210062064234,2024,11,F,1,1,1,1,10,NaN,0,4318903,São Luiz Gonzaga,43,RS,B,C,A,D,2,B,E,A,B,B,B,B,B,A,A,A,A,B,A,B,A,C,A
2,210062064235,2024,11,F,1,1,1,1,9,NaN,0,4320107,Sarandi,43,RS,H,F,F,D,5,B,J,A,C,D,B,B,C,A,B,B,B,D,B,B,A,D,A
3,210062064236,2024,3,F,1,3,1,2,0,1.0,0,4313409,Novo Hamburgo,43,RS,B,B,B,B,6,A,C,A,B,C,B,A,B,A,B,A,A,A,A,B,A,D,A
4,210062064237,2024,16,M,3,1,1,1,18,NaN,0,4309209,Gravataí,43,RS,B,B,C,C,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
5,210062064266,2024,12,M,2,1,1,1,3,NaN,0,4300604,Alvorada,43,RS,C,C,A,B,2,A,B,A,B,B,A,A,B,A,B,B,A,B,A,B,A,B,B
6,210062064267,2024,1,M,1,1,1,3,0,NaN,1,4307005,Erechim,43,RS,G,F,E,D,3,A,D,A,B,C,B,A,B,A,B,B,A,B,B,B,B,D,D
7,210062064268,2024,15,F,2,3,1,4,0,NaN,0,4312401,Montenegro,43,RS,B,B,F,F,2,B,C,A,B,B,B,A,B,A,B,B,A,A,A,B,A,B,F
8,210062064307,2024,16,M,3,1,1,1,18,NaN,0,4304606,Canoas,43,RS,B,C,B,C,1,B,C,A,B,B,B,A,B,A,A,B,A,B,A,A,B,B,B
9,210062064308,2024,11,F,1,3,1,1,10,NaN,0,4316907,Santa Maria,43,RS,E,B,C,B,2,A,E,A,B,D,A,A,B,A,B,B,B,B,B,B,B,C,A

In [10]:

df_participantes_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 38 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NU_INSCRICAO        1000 non-null   int64
 1   NU_ANO              1000 non-null   int64
 2   TP_FAIXA_ETARIA     1000 non-null   int64
 3   TP_SEXO             1000 non-null   str
 4   TP_ESTADO_CIVIL     1000 non-null   int64
 5   TP_COR_RACA         1000 non-null   int64
 6   TP_NACIONALIDADE    1000 non-null   int64
 7   TP_ST_CONCLUSAO     1000 non-null   int64
 8   TP_ANO_CONCLUIU     1000 non-null   int64
 9   TP_ENSINO           194 non-null    float64
 10  IN_TREINEIRO        1000 non-null   int64
 11  CO_MUNICIPIO_PROVA  1000 non-null   int64
 12  NO_MUNICIPIO_PROVA  1000 non-null   str
 13  CO_UF_PROVA         1000 non-null   int64
 14  SG_UF_PROVA         1000 non-null   str
 15  Q001                1000 non-null   str
 16  Q002                1000 non-null   str
 17  Q003                1000 non-null   str
 18  Q004                1000 non-null   str
 19  Q005                1000 non-null   int64
 20  Q006                1000 non-null   str
 21  Q007                1000 non-null   str
 22  Q008                1000 non-null   str
 23  Q009                1000 non-null   str
 24  Q010                1000 non-null   str
 25  Q011                1000 non-null   str
 26  Q012                1000 non-null   str
 27  Q013                1000 non-null   str
 28  Q014                1000 non-null   str
 29  Q015                1000 non-null   str
 30  Q016                1000 non-null   str
 31  Q017                1000 non-null   str
 32  Q018                1000 non-null   str
 33  Q019                1000 non-null   str
 34  Q020                1000 non-null   str
 35  Q021                1000 non-null   str
 36  Q022                1000 non-null   str
 37  Q023                1000 non-null   str
dtypes: float64(1), int64(12), str(25)
memory usage: 297.0 KB

In [11]:
df_participantes_2024.isnull().sum()

NU_INSCRICAO            0
NU_ANO                  0
TP_FAIXA_ETARIA         0
TP_SEXO                 0
TP_ESTADO_CIVIL         0
TP_COR_RACA             0
TP_NACIONALIDADE        0
TP_ST_CONCLUSAO         0
TP_ANO_CONCLUIU         0
TP_ENSINO             806
IN_TREINEIRO            0
CO_MUNICIPIO_PROVA      0
NO_MUNICIPIO_PROVA      0
CO_UF_PROVA             0
SG_UF_PROVA             0
Q001                    0
Q002                    0
Q003                    0
Q004                    0
Q005                    0
Q006                    0
Q007                    0
Q008                    0
Q009                    0
Q010                    0
Q011                    0
Q012                    0
Q013                    0
Q014                    0
Q015                    0
Q016                    0
Q017                    0
Q018                    0
Q019                    0
Q020                    0
Q021                    0
Q022                    0
Q023                    0
dtype: int64

In [47]:
df_participantes_2024.isnull().sum() [df_participantes_2024.isnull().sum() > 0].sort_values(ascending=False)

TP_ENSINO    806
dtype: int64

### `itens_prova_2024`

In [13]:
itens_prova_2024 = Path.cwd().parent / 'data' / 'raw' / '2024' / 'ITENS_PROVA_2024.csv'

df_itens_2024 = pd.read_csv(itens_prova_2024, encoding="latin-1", sep=";", nrows=1000)

In [14]:
df_itens_2024.head(10)

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
0,6,LC,150678,E,20,0,NaN,3.15898,0.16783,0.17207,AZUL,1395,NaN,0
1,7,LC,14475,D,1,0,NaN,2.36980,-0.23487,0.12324,AZUL,1353,NaN,0
2,7,LC,14475,D,1,0,NaN,2.36980,-0.23487,0.12324,AZUL,1441,NaN,0
3,7,LC,16575,A,16,0,NaN,3.04396,2.33757,0.08577,AMARELA,1354,NaN,0
4,7,LC,16575,A,16,0,NaN,3.04396,2.33757,0.08577,AMARELA,1442,NaN,0
5,7,LC,118297,B,17,0,NaN,2.32301,0.39677,0.16215,LARANJA,1401,NaN,1
6,7,LC,118297,B,17,0,NaN,2.32301,0.39677,0.16215,LARANJA,1402,NaN,1
7,7,LC,118297,B,17,0,NaN,2.32301,0.39677,0.16215,LEITOR TELA,1406,NaN,1
8,7,LC,118297,B,17,0,NaN,2.32301,0.39677,0.16215,ROXA,1403,NaN,0
9,7,LC,118297,B,17,0,NaN,2.32301,0.39677,0.16215,ROXA,1404,NaN,0

In [15]:
df_itens_2024.tail(10)

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
990,28,LC,140816,A,19,0,NaN,2.38400,1.68908,0.25667,VERDE,1445,NaN,0
991,28,LC,140816,A,19,0,NaN,2.38400,1.68908,0.25667,VERDE,1446,NaN,0
992,28,LC,140881,E,18,0,NaN,2.41000,1.38763,0.25068,AZUL,1395,NaN,0
993,28,LC,140886,E,15,0,NaN,2.48077,1.75332,0.23665,AZUL,1353,NaN,0
994,28,LC,140886,E,15,0,NaN,2.48077,1.75332,0.23665,AZUL,1441,NaN,0
995,28,LC,140961,A,17,0,NaN,1.21803,1.38698,0.10064,AMARELA,1396,NaN,0
996,28,LC,150460,D,25,0,NaN,2.24622,0.87521,0.18171,BRANCA,1356,NaN,0
997,28,LC,150460,D,25,0,NaN,2.24622,0.87521,0.18171,BRANCA,1444,NaN,0
998,28,LC,150666,E,27,0,NaN,3.54677,0.31786,0.12491,BRANCA,1398,NaN,0
999,29,LC,17182,B,15,0,NaN,2.18588,2.06747,0.20325,BRANCA,1398,NaN,0

In [16]:
df_itens_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CO_POSICAO        1000 non-null   int64
 1   SG_AREA           1000 non-null   str
 2   CO_ITEM           1000 non-null   int64
 3   TX_GABARITO       1000 non-null   str
 4   CO_HABILIDADE     1000 non-null   int64
 5   IN_ITEM_ABAN      1000 non-null   int64
 6   TX_MOTIVO_ABAN    14 non-null     str
 7   NU_PARAM_A        986 non-null    float64
 8   NU_PARAM_B        986 non-null    float64
 9   NU_PARAM_C        986 non-null    float64
 10  TX_COR            1000 non-null   str
 11  CO_PROVA          1000 non-null   int64
 12  TP_LINGUA         300 non-null    float64
 13  IN_ITEM_ADAPTADO  1000 non-null   int64
dtypes: float64(4), int64(6), str(4)
memory usage: 109.5 KB

In [17]:
df_itens_2024.isnull().sum()

CO_POSICAO            0
SG_AREA               0
CO_ITEM               0
TX_GABARITO           0
CO_HABILIDADE         0
IN_ITEM_ABAN          0
TX_MOTIVO_ABAN      986
NU_PARAM_A           14
NU_PARAM_B           14
NU_PARAM_C           14
TX_COR                0
CO_PROVA              0
TP_LINGUA           700
IN_ITEM_ADAPTADO      0
dtype: int64

## Interpretações


- A tabela de Resultados possui 2.767.147 valores NULLs referente as informações de escolaridade dos candidatos. Podemos inferir que o dataset contenha:

    1. Candidatos que já concluíram o ensino médio há anos e a escola não está mais ativa ou não tem registro no sistema do INEP. O ENEM não é só para quem está na escola, e qualquer pessoa com mais de 18 anos pode fazer;
    2. Candidatos que estudaram em escolas no exterior ou em sistemas de ensino não cadastrados no INEP;
    3. Treineiros: alunos que fazem o ENEM antes de concluir o ensino médio como treino. Eles podem ter escola mas o vínculo não estar preenchido;
    4. Problemas de cadastro: o participante não preencheu ou preencheu errado no momento da inscrição;

- Há uma variação na existência de valores na presença de candidatos entre os quatro âmbitos de prova (Redação + Linguagens, Matemática, Ciências Humanas e Ciências da Natureza). Comum visto que candidatos podem faltar em um dos dois dias de prova, ou ir em apenas um deles.
- As tabelas não possuem chave em comum conforme documentado no dicionário de dados do INEP, portanto serão tratadas e carregadas separadamente no banco.
- A tabela com as informações dos participantes possui poucos valores nulos para serem tratados;

    TB_ENSINO é a principal, onde contém o Tipo de instituição que o participante concluiu ou concluirá o Ensino Médio (fonte fácil de não ser colhida) 

    ```
    TP_ENSINO    2787062
    6               9
    8               1
    9               1
    6               1
    9               2
    ```
- A tabela de `participantes` possui um questionário socioecônomico que permite aprofundar as analises de desempenho de acordo com cada cenário social do participante;
- A grande maioria dos dados são integers ou floats — Isso significa que a base usa de códigos ENUM para representar os dados em boa parte dos atributos, exigindo estrutura de condições para facilitar a leitura;
- A base `itens_prova` contém dados sobre as questões dadas dentro da prova, o que pode nos dar informações sobre as dificuldades das questões e a influência sobre o desempenho dos participantes sobre elas.

##  Informações contidas nos dados de 2023

### `microdados_enem_2023`

In [18]:
microdados_2023 = Path.cwd().parent / 'data' / 'raw' / '2023' / 'MICRODADOS_ENEM_2023.csv' 

df_microdados_2023 = pd.read_csv(microdados_2023, encoding="latin-1", sep=";", nrows=1000)

In [19]:
df_microdados_2023.head(10)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210059085136,2023,14,M,2,1,1,1,17,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,F,E,D,5,F,C,C,D,C,D,C,B,B,D,C,C,B,B,A,B,B,A,A,B
1,210059527735,2023,12,M,2,1,0,1,16,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F,E,E,B,3,H,A,B,C,C,A,B,B,B,A,B,A,B,B,A,A,C,A,D,B
2,210061103945,2023,6,F,1,1,1,1,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4305108,Caxias do Sul,43,RS,1,1,1,1,1221.0,1193.0,1204.0,1211.0,502.0,498.9,475.6,363.2,DBEBDCECCBCEBBBBDBABDDBBAABCBACDBACECCBAADEBB,ABDEADAADCDABDCADAEABCDDCBAADCCBEBCEBEBDBEAED,ACEBDCABAACAEBAECEBBBAAECBBDEADCAECCCEDDABEED,CEAEACCCDABCDAACEDDBAAEBABDDEEBDAECABDBCBCADE,1,DBEABDABDCACDBECDDDBCAAABBACCCADEBECCCEDAEEED,ACEEABAADCDAADEABCDABCDCABCBDADEBAECABADBCDAE,DBABBAEBAAAACDACDEDAACADBADBCCEACCCEAAECBBEBCA...,BCCDEEABCBEDCEABBEBDABDDADDADECAADDCCBEBEABCC,1.0,140.0,200.0,100.0,120.0,140.0,700.0,H,E,C,F,5,C,A,B,D,B,A,B,A,B,A,B,A,A,B,A,A,A,A,A,B
3,210060214087,2023,2,F,1,3,1,2,0,2,1.0,0,2304400.0,Fortaleza,23.0,CE,2.0,1.0,1.0,2304400,Fortaleza,23,CE,1,1,1,1,1224.0,1192.0,1202.0,1214.0,459.0,508.5,507.2,466.7,DEEBEACCCEBDDBDCCCAEEDCBAAADBCBEEEDCDAAECBEEC,DDAAEEBCCDEADBCDDCBAECABEBDEBDABECECEDCDDAEED,ADBDADAEEEACAABBACADCAEBBAAEBBCDEBBDDADDCADAA,EECBAEDEEDDDBBAADEECDBBBECEAACEAEECDBEDDBCDCB,0,CDDDABBABDBEABDECCEEEDCEDAEBABDCCAACCCADACDBE,DBAADEADCDCABABCDDEBAEABAECABAACECDAECBDAABCD,BBBDAABAEACCEEEDEACBCACAACAACAAAECBBEDBCCADBDE...,EBDADDAEBEACBEDCECCBEABCADEBCCBCCDEBDDAABBADD,1.0,140.0,200.0,160.0,180.0,200.0,880.0,D,D,B,B,5,C,A,B,B,A,A,B,A,A,A,A,A,A,B,A,A,D,A,A,B
4,210059980948,2023,3,F,1,3,1,2,0,2,1.0,0,2311306.0,Quixadá,23.0,CE,2.0,1.0,1.0,2311306,Quixadá,23,CE,1,1,1,1,1222.0,1191.0,1201.0,1212.0,402.5,379.2,446.9,338.3,AECCEAACDEABEEECDBAEEAAADDEABCBCEBACEEDCBEABD,CADEBCEDDEBCBAEBADDCECACADBDEBABDBDBEEDBBEADC,AABBACBCAEDABDADEDAACCAEEEECAACDCADBAEACDEAAE,CDBABEDCEEBBBDECDEBACCAABDEDCBECDECABBDBDEECC,0,CAAADCCCCDDDABDCACDBEEEDCEDAEECCDBEABDBABBAEB,CDAEECABAACEAADECBDAABCDCABADCDEABAABCDDEBADB,BBDABAAEBADACEEDCCDBADBDEDCCEBCACEACAACAACACBB...,DCECACCBDECBEEABEABDDAADDABBBCCBCCDDAEBDADEEB,1.0,120.0,120.0,120.0,120.0,80.0,560.0,B,B,A,A,4,B,A,B,A,A,A,B,A,A,A,A,A,A,B,A,A,B,A,A,A
5,210058061539,2023,6,F,1,3,1,1,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2913606,Ilhéus,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,D,B,3,C,A,B,B,A,A,B,A,B,A,B,A,A,B,A,A,C,A,A,B
6,210059855122,2023,11,F,1,3,1,1,12,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611101,Petrolina,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,C,B,A,1,C,A,B,B,A,A,B,A,A,A,B,A,A,B,A,B,B,A,A,B
7,210058387333,2023,11,M,1,3,1,1,12,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3127701,Governador Valadares,31,MG,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,B,B,B,1,A,A,B,C,A,A,B,A,B,A,B,A,A,A,A,A,B,A,B,B
8,210059085137,2023,5,F,1,2,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2927408,Salvador,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,C,B,2,C,A,B,C,A,A,B,A,B,A,B,A,A,B,A,A,C,A,A,B
9,210060801601,2023,11,M,1,1,1,1,8,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3505906,Batatais,35,SP,1,1,1,1,1223.0,1194.0,1203.0,1213.0,564.7,630.3,610.4,680.2,CBAACDDEDEDEBCDDBACEACECECCEBBDCBEAEABCDBEADB,ABCDCBCACDBEACEBAABADAEBAADCBADBCDCEBADCDAADE,BDBBADAEDBEEACCAAADEACBBACCAEDCDAEEEBAEEDACCE,EBDDECEADDEBCCCCEACDDDCBDBDEAEABABDDCCBDCDACD,0,CEDAEEDEECCEBADCCCABBABCAACDDDACDBEABDCDBEABD,ABCDCBDACDAEACEECABADBEABADEBAABCDCABADCDAADE,BDBBABAAAEAAECBBEAACAAACEACBCACCCEDEDADBDBEEDD...,EBDEEBDADDABCCBCCABBADDBDDAEAEABCBEDECADCECCB,1.0,120.0,120.0,120.0,120.0,120.0,600.0,H,E,F,D,2,F,A,B,C,B,B,B,B,B,A,B,A,B,C,B,A,C,A,B,B

In [20]:
df_microdados_2023.tail(10)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
990,210059602757,2023,5,F,1,3,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4217709,Sombrio,42,SC,1,1,1,1,1221.0,1193.0,1204.0,1211.0,458.0,421.7,485.0,506.6,DBABBDCDDECCEBDAABDCDECDCBAEAACAEBDBDABAACBED,CADACADEECDBACEACADBD.CBEDACBBDAABACDEBDACCEA,ECEBEABECDAAEBAAEABAABCCDABAEDEEABABBECBDCAED,CDAEACDECACBDBEABDADACDEBCEDDCCDBABBDCEEAACCC,0,DBEABDABDCACDBECDDDBCAAABBACCCADEBECCCEDAEEED,ACEEABAADCDAADEABCDABCDCABCBDADEBAECABADBCDAE,DBABBAEBAAAACDACDEDAACADBADBCCEACCCEAAECBBEBCA...,BCCDEEABCBEDCEABBEBDABDDADDADECAADDCCBEBEABCC,1.0,120.0,120.0,140.0,180.0,180.0,740.0,B,E,A,B,5,C,B,B,C,B,A,A,A,B,A,A,A,A,B,A,A,B,A,A,B
991,210058954716,2023,7,M,1,3,1,1,4,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2303709,Caucaia,23,CE,1,1,1,1,1223.0,1194.0,1203.0,1213.0,554.8,477.6,564.2,560.9,CADADEBECBDDBCEDBABECBDAECEADACCEDCDBBCEBEBDA,ABCDBBDECAADABEABEBDCEACBDAAEBBACCAEDBCADEADB,BDBBAAABDDBEBECABAABACCBBCCBEDBDBDDEBAEDDADBD,EBEDEABACCBBDEBDCDACDDABCDEEEBCADBEDBEACBEDAC,0,CEDAEEDEECCEBADCCCABBABCAACDDDACDBEABDCDBEABD,ABCDCBDACDAEACEECABADBEABADEBAABCDCABADCDAADE,BDBBABAAAEAAECBBEAACAAACEACBCACCCEDEDADBDBEEDD...,EBDEEBDADDABCCBCCABBADDBDDAEAEABCBEDECADCECCB,1.0,100.0,120.0,120.0,120.0,140.0,600.0,C,E,B,B,4,B,A,B,C,A,B,B,A,A,A,A,A,A,B,A,A,D,A,A,B
992,210059974498,2023,11,F,3,1,1,1,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3549805,São José do Rio Preto,35,SP,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,E,C,B,5,A,A,B,B,A,A,B,B,A,A,A,A,A,B,A,A,B,A,A,A
993,210059897906,2023,9,M,1,1,1,1,6,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3126109,Formiga,31,MG,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,B,B,2,C,A,B,B,B,A,B,A,B,A,A,A,A,B,A,A,B,A,B,B
994,210060441023,2023,4,M,1,1,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2306553,Itarema,23,CE,1,1,1,1,1224.0,1192.0,1202.0,1214.0,583.5,585.2,585.7,665.5,ABBABBEDADBECDBACBEBABCBDABBDBCDEECECAEAAADEE,DBAADEBDCDCABCECDBEBCEAADACABEECBCDBEACDAACCE,BCBDADCDEEDCACCBCEAACAACAEAECBBEBDBCAECDDDDAD,EBDACDBEBEBDBACDDCCCECCCBCEACDDCCDBBBEECBDDCA,0,CDDDABBABDBEABDECCEEEDCEDAEBABDCCAACCCADACDBE,DBAADEADCDCABABCDDEBAEABAECABAACECDAECBDAABCD,BBBDAABAEACCEEEDEACBCACAACAACAAAECBBEDBCCADBDE...,EBDADDAEBEACBEDCECCBEABCADEBCCBCCDEBDDAABBADD,1.0,140.0,120.0,160.0,180.0,160.0,760.0,H,H,D,D,4,D,A,B,B,A,A,B,A,A,A,A,A,A,B,A,A,C,A,A,B
995,210060376454,2023,9,F,1,1,1,1,7,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2903201,Barreiras,29,BA,1,1,1,1,1224.0,1192.0,1202.0,1214.0,550.7,538.3,533.4,640.2,BEDDDACBADBEEBCEAAEAACDEDDBCCCCEDADECEADAEBEE,DBAADEABBDDBDECDAEBBDEDACCABEAACDCDAECADDEBCD,BDAEAACEEEBBEEBBDCAABBADBDABCDBEDBDCEEACEDDAC,EADAADEECECADADADCECEBBDBDCEDBCCDCBBCACEBEDDA,1,CDDDABBABDBEABDECCEEEDCEDAEBABDCCAACCCADACDBE,DBAADEADCDCABABCDDEBAEABAECABAACECDAECBDAABCD,BBBDAABAEACCEEEDEACBCACAACAACAAAECBBEDBCCADBDE...,EBDADDAEBEACBEDCECCBEABCADEBCCBCCDEBDDAABBADD,1.0,120.0,120.0,120.0,100.0,100.0,560.0,C,F,C,D,9,G,A,D,E,A,B,B,B,B,A,B,A,A,B,A,A,E,B,B,B
996,210059602759,2023,10,F,1,4,1,1,5,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2408102,Natal,24,RN,1,1,1,1,1222.0,1191.0,1201.0,1212.0,445.1,397.2,509.7,338.7,EDCEBCBAEEABCCABCEBAACEDDBBAEEDBEBEBAEAEDBBAC,EDBDCCDCBBEAECEEADDCADDAEEBCAEAECDBABDADDEBCA,ABEEADABCEDCDBBBADBDDACEEAADDEAEBEACBEACBEAAD,ECAABACBADBCEECDCBBDCEBCCEAEBEABDEACDCABCCBCA,1,CAAADCCCCDDDABDCACDBEEEDCEDAEECCDBEABDBABBAEB,CDAEECABAACEAADECBDAABCDCABADCDEABAABCDDEBADB,BBDABAAEBADACEEDCCDBADBDEDCCEBCACEACAACAACACBB...,DCECACCBDECBEEABEABDDAADDABBBCCBCCDDAEBDADEEB,1.0,120.0,140.0,120.0,120.0,40.0,540.0,D,C,B,B,2,B,A,B,C,A,A,B,A,A,A,A,A,A,C,A,A,C,A,A,B
997,210058954720,2023,3,F,1,1,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3520509,Indaiatuba,35,SP,1,1,1,1,1222.0,1191.0,1201.0,1212.0,480.1,543.9,518.8,427.9,BBBADCBAABBDDCBBAEEEECABCABACDCDEBACDBBACCCBC,CEBEBCACAADDAAAEDEDDABCCCDBEDBDCECEDBCAEEDEDB,BBAABDECAEDBDEBBBBDCACBDEAECCBECBEBADAEBBEDAA,BCDAECCDEBDBCEADCACCCEBCCECCBCACBDBAEEEDADDCE,0,CAAADCCCCDDDABDCACDBEEEDCEDAEECCDBEABDBABBAEB,CDAEECABAACEAADECBDAABCDCABADCDEABAABCDDEBADB,BBDABAAEBADACEEDCCDBADBDEDCCEBCACEACAACAACACBB...,DCECACCBDECBEEABEABDDAADDABBBCCBCCDDAEBDADEEB,1.0,160.0,100.0,160.0,160.0,80.0,660.0,C,E,B,C,2,D,A,C,C,B,B,B,B,B,A,B,A,B,B,A,A,C,B,B,B
998,210059974500,2023,4,F,1,1,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2608909,Limoeiro,26,PE,0,1,1,0,NaN,1193.0,1204.0,NaN,NaN,411.6,467.0,NaN,NaN,CAEEEBAEACDBCEACCDEAEBCEACBBDECABEDDCBACAEACA,BABEEDBCDEDDBDACBADDBDCBCBBEADEBAAEDCDDDCCBED,NaN,0,NaN,ACEEABAADCDAADEABCDABCDCABCBDADEBAECABADBCDAE,DBABBAEBAAAACDACDEDAACADBADBCCEACCCEAAECBBEBCA...,NaN,1.0,120.0,120.0,120.0,80.0,40.0,480.0,E,E,F,F,4,C,A,B,D,A,A,B,A,A,A,A,A,A,A,B,A,C,A,A,B
999,210059899838,2023,9,F,1,2,1,1,5,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2927408,Salvador,29,BA,1,1,1,1,1224.0,1192.0,1202.0,1214.0,504.3,459.2,585.7,634.8,ABDBAAEBBDBCEECCEDBCCBCDDABACCCDDACCBAAEABEED,DEBBDDEBCDCDADBEAEBAEEAAAACABADCDCDBACEECBDDC,DCBDACBEEEDEADDBACBBAAEEAAAEDCBEEBCCADBDBDDEC,EACACEBEBEDEDEDCEACCDCBDCCCCCCCDBDABDDBDBDDDD,0,CDDDABBABDBEABDECCEEEDCEDAEBABDCCAACCCADACDBE,DBAADEADCDCABABCDDEBAEABAECABAACECDAECBDAABCD,BBBDAABAEACCEEEDEACBCACAACAACAAAECBBEDBCCADBDE...,EBDADDAEBEACBEDCECCBEABCADEBCCBCCDEBDDAABBADD,1.0,120.0,200.0,180.0,180.0,180.0,860.0,H,E,F,D,4,D,A,B,C,A,A,B,B,A,A,B,A,A,B,A,A,E,A,B,B

In [21]:
df_microdados_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 76 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NU_INSCRICAO            1000 non-null   int64
 1   NU_ANO                  1000 non-null   int64
 2   TP_FAIXA_ETARIA         1000 non-null   int64
 3   TP_SEXO                 1000 non-null   str
 4   TP_ESTADO_CIVIL         1000 non-null   int64
 5   TP_COR_RACA             1000 non-null   int64
 6   TP_NACIONALIDADE        1000 non-null   int64
 7   TP_ST_CONCLUSAO         1000 non-null   int64
 8   TP_ANO_CONCLUIU         1000 non-null   int64
 9   TP_ESCOLA               1000 non-null   int64
 10  TP_ENSINO               233 non-null    float64
 11  IN_TREINEIRO            1000 non-null   int64
 12  CO_MUNICIPIO_ESC        145 non-null    float64
 13  NO_MUNICIPIO_ESC        145 non-null    str
 14  CO_UF_ESC               145 non-null    float64
 15  SG_UF_ESC               145 non-null    str
 16  TP_DEPENDENCIA_ADM_ESC  145 non-null    float64
 17  TP_LOCALIZACAO_ESC      145 non-null    float64
 18  TP_SIT_FUNC_ESC         145 non-null    float64
 19  CO_MUNICIPIO_PROVA      1000 non-null   int64
 20  NO_MUNICIPIO_PROVA      1000 non-null   str
 21  CO_UF_PROVA             1000 non-null   int64
 22  SG_UF_PROVA             1000 non-null   str
 23  TP_PRESENCA_CN          1000 non-null   int64
 24  TP_PRESENCA_CH          1000 non-null   int64
 25  TP_PRESENCA_LC          1000 non-null   int64
 26  TP_PRESENCA_MT          1000 non-null   int64
 27  CO_PROVA_CN             677 non-null    float64
 28  CO_PROVA_CH             701 non-null    float64
 29  CO_PROVA_LC             701 non-null    float64
 30  CO_PROVA_MT             677 non-null    float64
 31  NU_NOTA_CN              677 non-null    float64
 32  NU_NOTA_CH              701 non-null    float64
 33  NU_NOTA_LC              701 non-null    float64
 34  NU_NOTA_MT              677 non-null    float64
 35  TX_RESPOSTAS_CN         677 non-null    str
 36  TX_RESPOSTAS_CH         701 non-null    str
 37  TX_RESPOSTAS_LC         701 non-null    str
 38  TX_RESPOSTAS_MT         677 non-null    str
 39  TP_LINGUA               1000 non-null   int64
 40  TX_GABARITO_CN          677 non-null    str
 41  TX_GABARITO_CH          701 non-null    str
 42  TX_GABARITO_LC          701 non-null    str
 43  TX_GABARITO_MT          677 non-null    str
 44  TP_STATUS_REDACAO       701 non-null    float64
 45  NU_NOTA_COMP1           701 non-null    float64
 46  NU_NOTA_COMP2           701 non-null    float64
 47  NU_NOTA_COMP3           701 non-null    float64
 48  NU_NOTA_COMP4           701 non-null    float64
 49  NU_NOTA_COMP5           701 non-null    float64
 50  NU_NOTA_REDACAO         701 non-null    float64
 51  Q001                    1000 non-null   str
 52  Q002                    1000 non-null   str
 53  Q003                    1000 non-null   str
 54  Q004                    1000 non-null   str
 55  Q005                    1000 non-null   int64
 56  Q006                    1000 non-null   str
 57  Q007                    1000 non-null   str
 58  Q008                    1000 non-null   str
 59  Q009                    1000 non-null   str
 60  Q010                    1000 non-null   str
 61  Q011                    1000 non-null   str
 62  Q012                    1000 non-null   str
 63  Q013                    1000 non-null   str
 64  Q014                    1000 non-null   str
 65  Q015                    1000 non-null   str
 66  Q016                    1000 non-null   str
 67  Q017                    1000 non-null   str
 68  Q018                    1000 non-null   str
 69  Q019                    1000 non-null   str
 70  Q020                    1000 non-null   str
 71  Q021                    1000 non-null   str
 72  Q022                    1000 non-null   str
 73  Q023                    1000 non-null   str
 74  Q024                    1000 non-null   str
 75  Q025                    1000 non-null   str
dtypes: float64(21), int64(18), str(37)
memory usage: 593.9 KB

In [22]:
df_microdados_2023.isnull().sum()

NU_INSCRICAO       0
NU_ANO             0
TP_FAIXA_ETARIA    0
TP_SEXO            0
TP_ESTADO_CIVIL    0
                  ..
Q021               0
Q022               0
Q023               0
Q024               0
Q025               0
Length: 76, dtype: int64

In [23]:
df_microdados_2023.isnull().sum()[df_microdados_2023.isnull().sum() > 0].sort_values(ascending=False)

CO_MUNICIPIO_ESC          855
NO_MUNICIPIO_ESC          855
CO_UF_ESC                 855
TP_DEPENDENCIA_ADM_ESC    855
SG_UF_ESC                 855
TP_LOCALIZACAO_ESC        855
TP_SIT_FUNC_ESC           855
TP_ENSINO                 767
CO_PROVA_CN               323
NU_NOTA_CN                323
CO_PROVA_MT               323
TX_RESPOSTAS_MT           323
TX_GABARITO_CN            323
TX_RESPOSTAS_CN           323
NU_NOTA_MT                323
TX_GABARITO_MT            323
NU_NOTA_CH                299
CO_PROVA_CH               299
CO_PROVA_LC               299
NU_NOTA_LC                299
TX_RESPOSTAS_LC           299
TX_GABARITO_CH            299
TX_RESPOSTAS_CH           299
TX_GABARITO_LC            299
TP_STATUS_REDACAO         299
NU_NOTA_COMP1             299
NU_NOTA_COMP2             299
NU_NOTA_COMP3             299
NU_NOTA_COMP4             299
NU_NOTA_COMP5             299
NU_NOTA_REDACAO           299
dtype: int64

### `itens_prova_2023`

In [24]:
itens_prova_2023 = Path.cwd().parent / 'data' / 'raw' / '2023' / 'ITENS_PROVA_2023.csv' 

df_itens_2023 = pd.read_csv(itens_prova_2023, encoding="latin-1", sep=";", nrows=1000)

In [25]:
df_itens_2023.head(10)

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
0,21,LC,141283,B,14,0,NaN,2.20125,0.82582,0.21190,AMARELA,1286,NaN,0
1,20,LC,118144,C,23,0,NaN,2.43295,0.90091,0.13239,AMARELA,1286,NaN,0
2,11,LC,140926,D,26,0,NaN,1.95105,-0.13372,0.19557,AMARELA,1282,NaN,0
3,12,LC,36864,A,12,0,NaN,1.14733,0.38901,0.23027,ROSA,1243,NaN,0
4,5,LC,140614,C,8,0,NaN,2.25894,1.00728,0.17726,AMARELA,1286,0.0,0
5,117,CN,96496,B,17,0,NaN,3.65573,1.24080,0.31288,LARANJA,1308,NaN,1
6,12,LC,141215,D,12,0,NaN,2.56885,1.16647,0.14520,AMARELA,1282,NaN,0
7,34,LC,141406,D,29,0,NaN,2.58466,2.61160,0.17100,BRANCA,1284,NaN,0
8,20,LC,14727,D,16,0,NaN,2.10340,-0.07713,0.12881,BRANCA,1284,NaN,0
9,10,LC,140866,E,17,0,NaN,1.49999,1.57603,0.16120,AMARELA,1286,NaN,0

In [26]:
df_itens_2023.tail(10)

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
990,27,LC,141405,C,4,0,NaN,1.30934,-0.45847,0.20553,AMARELA,1246,NaN,0
991,177,MT,37312,D,4,0,NaN,1.84465,0.56332,0.22289,AZUL,1291,NaN,0
992,102,CN,54804,E,24,0,NaN,3.77630,1.61245,0.10238,VERDE,1317,NaN,0
993,116,CN,141760,D,13,0,NaN,2.42390,1.19043,0.26425,AMARELA,1302,NaN,0
994,100,CN,63407,C,20,0,NaN,1.67788,1.97964,0.28897,AMARELA,1302,NaN,0
995,100,CN,14943,A,5,0,NaN,1.62506,1.77927,0.09398,AMARELA,1306,NaN,0
996,103,CN,11309,C,8,0,NaN,1.62855,-1.00049,0.09528,ROSA,1264,NaN,0
997,81,CH,140576,B,21,0,NaN,1.33537,-0.77276,0.19854,LEITOR TELA,1280,NaN,0
998,38,LC,11815,C,13,0,NaN,1.24801,0.99800,0.19400,ROSA,1243,NaN,0
999,33,LC,140878,D,28,0,NaN,2.15451,0.45326,0.16205,ROSA,1243,NaN,0

In [27]:
df_itens_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CO_POSICAO        1000 non-null   int64
 1   SG_AREA           1000 non-null   str
 2   CO_ITEM           1000 non-null   int64
 3   TX_GABARITO       1000 non-null   str
 4   CO_HABILIDADE     1000 non-null   int64
 5   IN_ITEM_ABAN      1000 non-null   int64
 6   TX_MOTIVO_ABAN    0 non-null      float64
 7   NU_PARAM_A        1000 non-null   float64
 8   NU_PARAM_B        1000 non-null   float64
 9   NU_PARAM_C        1000 non-null   float64
 10  TX_COR            1000 non-null   str
 11  CO_PROVA          1000 non-null   int64
 12  TP_LINGUA         54 non-null     float64
 13  IN_ITEM_ADAPTADO  1000 non-null   int64
dtypes: float64(5), int64(6), str(3)
memory usage: 109.5 KB

In [28]:
df_itens_2023.isnull().sum()

CO_POSICAO             0
SG_AREA                0
CO_ITEM                0
TX_GABARITO            0
CO_HABILIDADE          0
IN_ITEM_ABAN           0
TX_MOTIVO_ABAN      1000
NU_PARAM_A             0
NU_PARAM_B             0
NU_PARAM_C             0
TX_COR                 0
CO_PROVA               0
TP_LINGUA            946
IN_ITEM_ADAPTADO       0
dtype: int64

### Interpretações

- Os dados contidos no dataset de 2023 são enxutados em apenas um relação, diferente dos do ano de 2024, cujo foram separados em tabelas diferentes. Por isso, possuimos uma única base com dados do participante, da escola estudada, desempenho na prova e questionário socioecônomico;
- Assim como dataset anterior ele possui maior quantidade de valores nulos com os atributos que se referem aos dados escoares, e por segundo, uma diferença entre os dois dias de prova;   
- No demais, a estrutura segue parecida com o dataset de 2024, possuinto muitos integers para representação de valores, exigindo o uso do dicionário de dados
- Tx_respostas representa um valor alto de nulos, visto que significa a taxa de questões vetadas por alguma infração, ou seja, muitos não tiveram nenhuma alternativa vetada;
- Possuimos alguns valores nulos dentro das colunas que representam as notas dos alunos. Vale verificar se são provas anuladas;
- Código do tipo de prova apresenta alta quantidade de valores nulos também, o que pode ser um atributo sem constância de preenchimento;
- Devido a estrutura de uma única tabela, podemos fazer analises que vinculam as informações dos participantes e o resultado das suas provas (diferente do dataset de 2024).

##  Informações contidas nos dados de 2022

### `microdados_enem_2022`

In [29]:
microdados_2022 = Path.cwd().parent / 'data' / 'raw' / '2022' / 'MICRODADOS_ENEM_2022.csv'

df_microdados_2022 = pd.read_csv(microdados_2022, encoding='latin-1', sep=';', nrows=1000)

In [30]:
df_microdados_2022.head(10)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210057943671,2022,14,M,2,2,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,A,A,B,3,B,B,B,B,B,B,B,A,B,B,B,A,A,A,A,A,A,A,A,A
1,210057516120,2022,14,M,2,1,1,1,16,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,E,E,3,Q,D,E,E,E,E,E,E,E,E,E,E,B,E,B,B,E,B,E,B
2,210057280536,2022,5,F,1,2,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2925758,Presidente Tancredo Neves,29,BA,1,1,1,1,1087.0,1056.0,1066.0,1078.0,421.1,546.0,498.8,565.3,DCDCEBADDABEDBCBEAEACCDDECEEBECBECAAECDDDDBCE,DBDABCADADECACBDCCEDACCCECDDABDCEADABCBCBAEAB,ABEABADCCADCAAAACDADDCECBAAACADABDEBCBCAAACEB,BDEBACECBCAEBABEDBABDACBCABCDEDEADBAABCBEACCD,1,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,140.0,200.0,120.0,140.0,160.0,760.0,E,F,A,D,2,B,A,B,C,A,A,B,B,A,A,A,A,A,A,A,A,C,A,A,B
3,210055724397,2022,6,M,1,3,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3201308,Cariacica,32,ES,1,1,1,1,1088.0,1058.0,1067.0,1077.0,490.7,388.6,357.8,416.0,BACBBABBCAABCABBCBACBCBCBACABACABCBDBCBABAACA,BBCAACACDCABCBACCABABCBACBCABBBBBABCBACCBCBBA,ABACCCCBCBAADABBBACABBAABACCBCBBCDCACABABCAAC,BBBACCBABABBBBACDABBBBABCCBBCABBBBAACABBACBCB,1,DDCBBCCDDAADBAABEDABCEEAEBAEBECBDDEBEACCEACCD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,CDBEDACDEACAABDBDBDDCABEEECEABECABEEAAACBBEBAD...,CCCCBXCBABECBEABDDDBDECDBDCAACEECCEBDBAAAEDAE,1.0,120.0,40.0,40.0,100.0,20.0,320.0,C,A,A,B,3,A,A,C,D,A,A,B,A,B,A,B,A,A,C,A,A,C,B,B,B
4,210055097896,2022,4,M,0,3,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1506203,Salinópolis,15,PA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,B,A,B,2,B,A,B,B,A,A,B,A,A,A,A,A,A,A,A,A,B,A,A,A
5,210057850231,2022,5,F,1,3,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3304557,Rio de Janeiro,33,RJ,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,C,B,B,4,C,A,C,C,A,A,B,B,B,A,B,A,A,C,A,B,D,A,A,B
6,210056305481,2022,4,M,1,2,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2611606,Recife,26,PE,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,B,B,B,3,B,A,B,D,A,A,B,A,A,A,A,A,A,C,A,A,C,A,A,B
7,210055778089,2022,6,F,1,2,1,1,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3304904,São Gonçalo,33,RJ,1,1,1,1,1086.0,1055.0,1065.0,1076.0,398.1,427.3,400.2,404.9,CBCCDBCACACABBDAEACBCBBCBCBABBBBDDCBCCCACACDB,BABACCABCBADEABDDBABDEBABDABABCEDCBBDADECACAC,DACECBAEAABBEAACDCCBAEBEBABCCDCBEEDAABDCADBEB,DBCCABCCBCEEBCECBEBEACAABACBBBCBCBBCAEBACEBBC,1,EACDDEBEACCCDABCEECBBCCAEBEDABEADBADDCBDDAAEB,DEABEEDAEBAAECBECBABCDDAAADBCEDAEACDBBCDCBECA,DCBDEEDCAAEAAACABBDBEBACCBEEECCBBDCAAADCCABEDB...,DBAAACEBEDAECCBECDEECBDCABECBEABDDCCDBDXCBAAC,1.0,100.0,120.0,80.0,100.0,40.0,440.0,E,E,B,B,5,B,A,B,C,B,A,C,B,A,A,B,A,A,C,A,A,E,A,A,B
8,210057252239,2022,8,F,1,3,1,1,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2901007,Amargosa,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,D,A,A,5,B,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,B,A,A,B
9,210055461467,2022,4,F,1,3,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2601201,Arcoverde,26,PE,1,1,1,1,1087.0,1056.0,1066.0,1078.0,467.5,461.0,466.7,435.3,ACEAACADAEBADDCCACACBBCDEDEDABDBDAACBCBBDCACB,EAAABEADCDDCEAACDCAECACDCBAECAECEDCABCEDDDBAE,ECEABCBECEDACADABDCBDEEBBABEBCDAABBBDABCDACBE,BEBCCCABABCCDCCCBECEBEDEACBEDCBBDCDCDBADACBAA,1,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,80.0,80.0,80.0,80.0,40.0,360.0,E,E,B,B,2,B,A,B,B,A,A,B,A,A,A,A,A,A,B,A,A,B,A,A,B

In [31]:
df_microdados_2022.tail(10)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
990,210056578908,2022,2,F,1,3,1,3,0,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928109,Santa Maria da Vitória,29,BA,1,1,1,1,1088.0,1058.0,1067.0,1077.0,502.2,592.8,542.4,645.8,DDDEACADEAADDDDACBCCBABECCACAACDADABABECDCDAD,BDDAAADCDEBBCADADEAABBDDCCADADCABBDDECEEBDADC,CDBEBCAABDBDBDDADEBADCCDDCCCBCEBEADBCDDCDBEDD,CBDCBEDDDCBCBBAADDBDCBCDAEBEADBCDECBBBEADBDAD,0,DDCBBCCDDAADBAABEDABCEEAEBAEBECBDDEBEACCEACCD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,CDBEDACDEACAABDBDBDDCABEEECEABECABEEAAACBBEBAD...,CCCCBXCBABECBEABDDDBDECDBDCAACEECCEBDBAAAEDAE,1.0,160.0,200.0,200.0,200.0,200.0,960.0,C,E,D,D,3,G,A,D,D,B,A,B,B,B,B,B,A,A,C,B,A,C,A,B,B
991,210055549343,2022,1,F,1,3,1,3,0,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3161106,São Francisco,31,MG,1,1,1,1,1088.0,1058.0,1067.0,1077.0,448.3,428.2,390.5,415.5,CDEEAECBDCBCDACBCDDBECDCBABADDBCDDDBEBAABADBC,CDEBBCCBCCECEBBBDCEAEACDAAEDBCBACEDCEBCABEADE,EBBCCCABCCBBAAAAAAECBACAABBDBCBACADADBAECCCED,ECACEDBDDBBBBBCEEABCAEADBBBABABECBDECCACABCEE,1,DDCBBCCDDAADBAABEDABCEEAEBAEBECBDDEBEACCEACCD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,CDBEDACDEACAABDBDBDDCABEEECEABECABEEAAACBBEBAD...,CCCCBXCBABECBEABDDDBDECDBDCAACEECCEBDBAAAEDAE,1.0,120.0,160.0,100.0,120.0,120.0,620.0,C,D,F,F,5,B,A,B,E,A,B,B,A,B,A,A,A,A,A,A,A,D,A,B,B
992,210056189856,2022,1,F,1,3,1,3,0,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2106326,Maracaçumé,21,MA,1,1,1,1,1085.0,1057.0,1068.0,1075.0,441.2,509.3,577.2,470.9,DECEAEECABBAECCEECEDACDEAACECEADAABCEDCEBEDCC,DCDEEEADDAACBEBAAAEECBCCDAACCBBECEABAEDCADCAC,ABDCECCDDACDBCCBABBACEDEBADAECCBACDAAEBDDDBAA,DEEDBBBDACBDDEAABCDCBAABBECCCCACCAECCEEABABBA,1,ADBADABEABCEEEACCBDDADDCBBCCAEBAEBEBEACCCDDDE,CBECABBCDEACDCEDAAADBCDDAECBABAECBEBAEEDADEAB,BDECDAADCECCCDCCEBACBBAAAEECABABEECEBEEDCADBDB...,ECDABEBDCEECDBDCCCCBCXCBAACDBAAACEBABDDEDAEBE,8.0,0.0,0.0,0.0,0.0,0.0,0.0,A,A,A,B,5,A,A,B,B,A,A,B,A,A,A,A,A,A,B,A,A,A,A,A,A
993,210057607998,2022,4,F,1,1,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4307005,Erechim,43,RS,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,F,A,D,1,D,A,B,B,A,A,B,A,B,B,A,A,A,B,A,B,B,A,B,B
994,210054669776,2022,11,M,1,1,1,2,0,2,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4314407,Pelotas,43,RS,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,F,F,2,A,A,A,B,A,A,A,A,A,A,A,A,A,B,A,A,A,A,A,A
995,210055642015,2022,6,M,1,3,1,1,4,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2801009,Campo do Brito,28,SE,1,1,1,1,1087.0,1056.0,1066.0,1078.0,400.0,537.4,500.0,493.9,BCDACCBDCCBCBBCACBEDCCABDAEABABBE*CBECADBEBCD,EDAABADDADCBEBADCEDDAAACECBCAC*CDDAABEADDCAEE,EAEADDCBCABEDEDAADECEBDEEDBACEBADCBCBDCCDBBEB,BDDBACCBCBCDCABCCDBEBBCACDBEECDBCEBBADBEDABBE,1,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,100.0,160.0,140.0,120.0,180.0,700.0,B,B,A,A,2,B,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,C,A,B,B
996,210055591467,2022,3,M,1,2,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2704302,Maceió,27,AL,1,1,1,1,1088.0,1058.0,1067.0,1077.0,443.9,544.9,529.7,484.4,DADCCAEEEEDEBBEBBCACBACBCEBABCEBCDECADCCDBDAC,DBDEAADBDCBBBEDDDEACBBDEBCBAAEEACBEEEBEEBCCCA,ACDEEDABDDEEBDCDADAEACBACAEDBBEDEABBDBDEDCCCB,DDABC*CADEBBBDDEDABBCBDEDAEEEDDCDBBEBDCEEEAAC,1,DDCBBCCDDAADBAABEDABCEEAEBAEBECBDDEBEACCEACCD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,CDBEDACDEACAABDBDBDDCABEEECEABECABEEAAACBBEBAD...,CCCCBXCBABECBEABDDDBDECDBDCAACEECCEBDBAAAEDAE,1.0,140.0,140.0,120.0,120.0,120.0,640.0,C,D,D,D,3,C,A,C,D,B,A,B,B,B,A,A,A,A,D,B,A,D,A,B,B
997,210057387803,2022,2,M,1,1,1,2,0,2,1.0,0,2603454.0,Camaragibe,26.0,PE,2.0,1.0,1.0,2603454,Camaragibe,26,PE,1,1,1,1,1087.0,1056.0,1066.0,1078.0,561.4,573.7,579.1,600.4,DEDADBEBECBABBCBCACCDDDCADEECCAEBAACDBEBDACCD,ECBABEDDDBBBBDEBCEEDABACDEADACBDDDCACDECDCACE,DDCDBDDBCADAAEAAADBCEADDBBBAADAEBDCCDEABEECBA,BEEBABAADBBDBACCEEECBDCADBDBCBDDBCDDEBADCBBBC,0,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,140.0,120.0,120.0,120.0,100.0,600.0,H,G,B,E,3,C,A,B,C,A,B,B,B,B,B,B,A,A,B,A,A,D,A,B,B
998,210057257170,2022,8,F,1,2,1,1,5,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2930501,Serrinha,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,C,A,A,6,A,A,B,D,A,B,B,A,A,A,A,A,A,B,A,A,C,A,A,B
999,210054718093,2022,3,M,1,1,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4322400,Uruguaiana,43,RS,1,1,1,1,1087.0,1056.0,1066.0,1078.0,581.1,613.5,617.7,603.0,CDACDCBAEBAABADBBBCCBECCCEEBDEBDDDCBCEBBAADDB,EABACBDDAAEABBEBEEEBAECCDEEDABEDDCEABDEDACACD,DECDBCDBCCAAEDAAEDCCAAEEBBBAAAAABDBCCCBBCECBD,BEEDACACDACDDCADAEBCADEBBCBADCBECCBBABCADBBCA,0,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,140.0,200.0,140.0,160.0,160.0,800.0,E,C,B,C,7,C,A,B,C,C,B,B,B,B,A,B,A,A,B,A,A,C,A,A,B

In [32]:
df_microdados_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 76 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NU_INSCRICAO            1000 non-null   int64
 1   NU_ANO                  1000 non-null   int64
 2   TP_FAIXA_ETARIA         1000 non-null   int64
 3   TP_SEXO                 1000 non-null   str
 4   TP_ESTADO_CIVIL         1000 non-null   int64
 5   TP_COR_RACA             1000 non-null   int64
 6   TP_NACIONALIDADE        1000 non-null   int64
 7   TP_ST_CONCLUSAO         1000 non-null   int64
 8   TP_ANO_CONCLUIU         1000 non-null   int64
 9   TP_ESCOLA               1000 non-null   int64
 10  TP_ENSINO               239 non-null    float64
 11  IN_TREINEIRO            1000 non-null   int64
 12  CO_MUNICIPIO_ESC        141 non-null    float64
 13  NO_MUNICIPIO_ESC        141 non-null    str
 14  CO_UF_ESC               141 non-null    float64
 15  SG_UF_ESC               141 non-null    str
 16  TP_DEPENDENCIA_ADM_ESC  141 non-null    float64
 17  TP_LOCALIZACAO_ESC      141 non-null    float64
 18  TP_SIT_FUNC_ESC         141 non-null    float64
 19  CO_MUNICIPIO_PROVA      1000 non-null   int64
 20  NO_MUNICIPIO_PROVA      1000 non-null   str
 21  CO_UF_PROVA             1000 non-null   int64
 22  SG_UF_PROVA             1000 non-null   str
 23  TP_PRESENCA_CN          1000 non-null   int64
 24  TP_PRESENCA_CH          1000 non-null   int64
 25  TP_PRESENCA_LC          1000 non-null   int64
 26  TP_PRESENCA_MT          1000 non-null   int64
 27  CO_PROVA_CN             620 non-null    float64
 28  CO_PROVA_CH             674 non-null    float64
 29  CO_PROVA_LC             674 non-null    float64
 30  CO_PROVA_MT             620 non-null    float64
 31  NU_NOTA_CN              620 non-null    float64
 32  NU_NOTA_CH              674 non-null    float64
 33  NU_NOTA_LC              674 non-null    float64
 34  NU_NOTA_MT              620 non-null    float64
 35  TX_RESPOSTAS_CN         620 non-null    str
 36  TX_RESPOSTAS_CH         674 non-null    str
 37  TX_RESPOSTAS_LC         674 non-null    str
 38  TX_RESPOSTAS_MT         620 non-null    str
 39  TP_LINGUA               1000 non-null   int64
 40  TX_GABARITO_CN          620 non-null    str
 41  TX_GABARITO_CH          674 non-null    str
 42  TX_GABARITO_LC          674 non-null    str
 43  TX_GABARITO_MT          620 non-null    str
 44  TP_STATUS_REDACAO       674 non-null    float64
 45  NU_NOTA_COMP1           674 non-null    float64
 46  NU_NOTA_COMP2           674 non-null    float64
 47  NU_NOTA_COMP3           674 non-null    float64
 48  NU_NOTA_COMP4           674 non-null    float64
 49  NU_NOTA_COMP5           674 non-null    float64
 50  NU_NOTA_REDACAO         674 non-null    float64
 51  Q001                    1000 non-null   str
 52  Q002                    1000 non-null   str
 53  Q003                    1000 non-null   str
 54  Q004                    1000 non-null   str
 55  Q005                    1000 non-null   int64
 56  Q006                    1000 non-null   str
 57  Q007                    1000 non-null   str
 58  Q008                    1000 non-null   str
 59  Q009                    1000 non-null   str
 60  Q010                    1000 non-null   str
 61  Q011                    1000 non-null   str
 62  Q012                    1000 non-null   str
 63  Q013                    1000 non-null   str
 64  Q014                    1000 non-null   str
 65  Q015                    1000 non-null   str
 66  Q016                    1000 non-null   str
 67  Q017                    1000 non-null   str
 68  Q018                    1000 non-null   str
 69  Q019                    1000 non-null   str
 70  Q020                    1000 non-null   str
 71  Q021                    1000 non-null   str
 72  Q022                    1000 non-null   str
 73  Q023                    1000 non-null   str
 74  Q024                    1000 non-null   str
 75  Q025                    1000 non-null   str
dtypes: float64(21), int64(18), str(37)
memory usage: 593.9 KB

In [33]:
df_microdados_2022.isnull().sum()

NU_INSCRICAO       0
NU_ANO             0
TP_FAIXA_ETARIA    0
TP_SEXO            0
TP_ESTADO_CIVIL    0
                  ..
Q021               0
Q022               0
Q023               0
Q024               0
Q025               0
Length: 76, dtype: int64

In [48]:
df_microdados_2022.isnull().sum() [df_microdados_2022.isnull().sum() > 0].sort_values(ascending=False)

CO_MUNICIPIO_ESC          859
NO_MUNICIPIO_ESC          859
CO_UF_ESC                 859
TP_DEPENDENCIA_ADM_ESC    859
SG_UF_ESC                 859
TP_LOCALIZACAO_ESC        859
TP_SIT_FUNC_ESC           859
TP_ENSINO                 761
CO_PROVA_CN               380
NU_NOTA_CN                380
CO_PROVA_MT               380
TX_RESPOSTAS_MT           380
TX_GABARITO_CN            380
TX_RESPOSTAS_CN           380
NU_NOTA_MT                380
TX_GABARITO_MT            380
NU_NOTA_CH                326
CO_PROVA_CH               326
CO_PROVA_LC               326
NU_NOTA_LC                326
TX_RESPOSTAS_LC           326
TX_GABARITO_CH            326
TX_RESPOSTAS_CH           326
TX_GABARITO_LC            326
TP_STATUS_REDACAO         326
NU_NOTA_COMP1             326
NU_NOTA_COMP2             326
NU_NOTA_COMP3             326
NU_NOTA_COMP4             326
NU_NOTA_COMP5             326
NU_NOTA_REDACAO           326
dtype: int64

### `itens_prova_2022`

In [35]:
itens_prova_2022 = Path.cwd().parent / 'data' / 'raw' / '2022' / 'ITENS_PROVA_2022.csv'

df_itens_2022 = pd.read_csv (itens_prova_2022, encoding='latin-1', sep=';', nrows=1000)

In [36]:
df_itens_2022.head(10)

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
0,46,CH,140506,D,26,0,NaN,0.98121,1.34897,0.06218,AZUL,1055,NaN,0
1,90,CH,111984,A,3,0,NaN,1.90716,1.36087,0.22521,AZUL,1055,NaN,0
2,89,CH,140190,C,5,0,NaN,1.94428,0.27387,0.14788,AZUL,1055,NaN,0
3,88,CH,96516,E,2,0,NaN,1.96743,2.20588,0.08863,AZUL,1055,NaN,0
4,87,CH,140572,B,19,0,NaN,2.46583,0.73772,0.17053,AZUL,1055,NaN,0
5,86,CH,96291,C,1,0,NaN,2.90370,1.66082,0.10307,AZUL,1055,NaN,0
6,85,CH,125944,D,4,0,NaN,1.69059,0.29126,0.11660,AZUL,1055,NaN,0
7,84,CH,111893,C,3,0,NaN,0.56617,1.58010,0.03472,AZUL,1055,NaN,0
8,83,CH,141072,B,8,0,NaN,2.78275,0.64418,0.18557,AZUL,1055,NaN,0
9,82,CH,140643,B,6,0,NaN,2.21197,1.42360,0.21778,AZUL,1055,NaN,0

In [37]:
df_itens_2022.tail(10)

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
990,136,MT,85588,B,24,0,NaN,2.30031,0.46698,0.25799,CINZA,1078,NaN,0
991,180,MT,30493,D,27,0,NaN,0.80375,2.27556,0.12859,CINZA,1078,NaN,0
992,179,MT,86840,C,28,0,NaN,0.24441,4.65334,0.03228,CINZA,1078,NaN,0
993,178,MT,97590,E,25,0,NaN,2.33252,2.40899,0.14217,CINZA,1078,NaN,0
994,177,MT,89637,E,28,1,Convergência,NaN,NaN,NaN,CINZA,1078,NaN,0
995,176,MT,10500,B,3,0,NaN,1.57712,3.30111,0.16855,CINZA,1078,NaN,0
996,175,MT,117973,A,11,0,NaN,1.87291,2.86025,0.18347,CINZA,1078,NaN,0
997,174,MT,75829,C,1,0,NaN,1.18017,1.92189,0.16856,CINZA,1078,NaN,0
998,173,MT,5961,D,7,0,NaN,0.90320,2.45135,0.16170,CINZA,1078,NaN,0
999,172,MT,86499,B,5,0,NaN,2.93676,3.33565,0.21207,CINZA,1078,NaN,0

In [38]:
df_itens_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CO_POSICAO        1000 non-null   int64
 1   SG_AREA           1000 non-null   str
 2   CO_ITEM           1000 non-null   int64
 3   TX_GABARITO       1000 non-null   str
 4   CO_HABILIDADE     1000 non-null   int64
 5   IN_ITEM_ABAN      1000 non-null   int64
 6   TX_MOTIVO_ABAN    16 non-null     str
 7   NU_PARAM_A        984 non-null    float64
 8   NU_PARAM_B        984 non-null    float64
 9   NU_PARAM_C        984 non-null    float64
 10  TX_COR            1000 non-null   str
 11  CO_PROVA          1000 non-null   int64
 12  TP_LINGUA         90 non-null     float64
 13  IN_ITEM_ADAPTADO  1000 non-null   int64
dtypes: float64(4), int64(6), str(4)
memory usage: 109.5 KB

In [39]:
df_itens_2022.isnull().sum()

CO_POSICAO            0
SG_AREA               0
CO_ITEM               0
TX_GABARITO           0
CO_HABILIDADE         0
IN_ITEM_ABAN          0
TX_MOTIVO_ABAN      984
NU_PARAM_A           16
NU_PARAM_B           16
NU_PARAM_C           16
TX_COR                0
CO_PROVA              0
TP_LINGUA           910
IN_ITEM_ADAPTADO      0
dtype: int64

In [49]:
df_itens_2022.isnull().sum() [df_itens_2022.isnull().sum() > 0].sort_values(ascending=False)

TX_MOTIVO_ABAN    984
TP_LINGUA         910
NU_PARAM_A         16
NU_PARAM_B         16
NU_PARAM_C         16
dtype: int64

### `quest_hab_estudo.csv`

In [41]:
quest_hab_estudo = Path.cwd().parent / 'data' / 'raw' / '2022' / 'QUEST_HAB_ESTUDO.csv'

df_quest_hab_estudo = pd.read_csv(quest_hab_estudo, encoding='latin-1', sep=';', nrows=1000)

In [42]:
df_quest_hab_estudo.head(10)

,NU_INSCRICAO,TP_RESPOSTA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025A,Q025B,Q025C,Q025D,Q025E,Q025F,Q026A,Q026B,Q026C,Q026D,Q026E,Q026F,Q026G,Q026H,Q027,Q028A,Q028B,Q028C,Q028D,Q028E,Q028F,Q028G,Q028H,Q028I,Q028J,Q028K,Q028L,Q028M,Q028N,Q028O,Q028P,Q028Q,Q028R,Q029,Q030A,Q030B,Q030C,Q030D,Q030E,Q030F,Q030G,Q031,Q032A,Q032B,Q032C,Q032D,Q032E,Q032F,Q032G,Q033A,Q033B,Q033C,Q033D,Q033E,Q033F,Q033G,Q033H,Q033I,Q033J,Q034
0,210054478229,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,210054478230,1,D,NaN,D,C,A,B,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,B,B,B,B,B,B,B,A,B,B,B,B,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,A,B,B,B,B,B,B,B,B,B,B,B,B,A,B,B,B,A
2,210054478234,1,D,NaN,E,E,C,C,C,B,B,B,B,B,B,B,B,C,B,B,B,B,A,A,B,B,B,B,B,B,A,B,B,B,B,A,B,B,B,B,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,A,B,B,B,B,B,B,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B
3,210054478235,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,210054478236,1,A,A,B,D,B,B,B,B,A,B,A,A,B,C,A,A,B,A,A,B,A,B,B,A,B,B,A,B,A,B,B,B,A,A,B,B,B,B,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,B,A,B,A,B,B,B,A,A,B,B,B,B,B,A,B,B,B,B,B,B,A,B,B,A,B
5,210054478237,1,D,NaN,D,E,D,C,C,C,D,D,D,D,D,D,D,D,D,D,D,B,A,A,C,A,B,B,B,B,B,A,B,B,B,B,B,A,B,B,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E
6,210054478238,1,D,NaN,D,F,A,A,B,B,A,B,B,B,B,B,C,C,C,C,C,A,B,B,B,B,B,A,B,B,A,B,B,B,B,A,B,B,A,B,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,B,A,A,B,B,B,B,B,B,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B
7,210054478239,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,210054478240,1,E,NaN,D,C,B,B,B,B,B,B,C,A,B,A,A,A,A,B,B,A,B,B,B,B,B,B,B,B,A,B,B,A,B,B,B,B,B,B,A,B,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,A,B,B,B,B,B,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B
9,210054478241,1,E,NaN,E,E,B,A,B,B,B,D,C,B,B,B,C,C,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df_quest_hab_estudo.tail(10)

,NU_INSCRICAO,TP_RESPOSTA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025A,Q025B,Q025C,Q025D,Q025E,Q025F,Q026A,Q026B,Q026C,Q026D,Q026E,Q026F,Q026G,Q026H,Q027,Q028A,Q028B,Q028C,Q028D,Q028E,Q028F,Q028G,Q028H,Q028I,Q028J,Q028K,Q028L,Q028M,Q028N,Q028O,Q028P,Q028Q,Q028R,Q029,Q030A,Q030B,Q030C,Q030D,Q030E,Q030F,Q030G,Q031,Q032A,Q032B,Q032C,Q032D,Q032E,Q032F,Q032G,Q033A,Q033B,Q033C,Q033D,Q033E,Q033F,Q033G,Q033H,Q033I,Q033J,Q034
990,210054480080,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
991,210054480081,1,A,A,A,B,C,B,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,D,C,C,B,A,B,B,B,B,B,B,B,A,B,B,B,B,A,B,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,B,A,B,B,B,B,B,A,B,B,B,A,B,B,B,B,A,B,B,B,B,B,B,B,B,C
992,210054480082,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,210054480089,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,210054480091,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,210054480093,1,A,A,C,C,C,B,C,B,C,B,D,B,D,B,C,C,C,C,C,A,C,C,C,B,B,A,B,B,A,B,B,B,B,A,B,B,B,B,A,B,B,B,B,B,B,A,A,B,B,B,B,B,B,B,B,B,B,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C
996,210054480094,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,210054480095,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,210054480096,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,210054480101,1,E,NaN,E,F,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,B,B,A,B,B,B,B,A,B,B,B,A,B,B,B,B,B,B,A,B,A,B,B,B,B,B,B,B,B,B,A,A,B,B,A,B,B,B,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [44]:
df_quest_hab_estudo.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 86 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NU_INSCRICAO  1000 non-null   int64
 1   TP_RESPOSTA   1000 non-null   int64
 2   Q001          359 non-null    str
 3   Q002          149 non-null    str
 4   Q003          326 non-null    str
 5   Q004          312 non-null    str
 6   Q005          306 non-null    str
 7   Q006          302 non-null    str
 8   Q007          301 non-null    str
 9   Q008          299 non-null    str
 10  Q009          295 non-null    str
 11  Q010          290 non-null    str
 12  Q011          289 non-null    str
 13  Q012          289 non-null    str
 14  Q013          285 non-null    str
 15  Q014          282 non-null    str
 16  Q015          281 non-null    str
 17  Q016          277 non-null    str
 18  Q017          274 non-null    str
 19  Q018          273 non-null    str
 20  Q019          270 non-null    str
 21  Q020          267 non-null    str
 22  Q021          267 non-null    str
 23  Q022          267 non-null    str
 24  Q023          266 non-null    str
 25  Q024          266 non-null    str
 26  Q025A         265 non-null    str
 27  Q025B         265 non-null    str
 28  Q025C         265 non-null    str
 29  Q025D         265 non-null    str
 30  Q025E         265 non-null    str
 31  Q025F         265 non-null    str
 32  Q026A         265 non-null    str
 33  Q026B         265 non-null    str
 34  Q026C         265 non-null    str
 35  Q026D         265 non-null    str
 36  Q026E         265 non-null    str
 37  Q026F         265 non-null    str
 38  Q026G         265 non-null    str
 39  Q026H         265 non-null    str
 40  Q027          265 non-null    str
 41  Q028A         190 non-null    str
 42  Q028B         190 non-null    str
 43  Q028C         190 non-null    str
 44  Q028D         190 non-null    str
 45  Q028E         190 non-null    str
 46  Q028F         190 non-null    str
 47  Q028G         190 non-null    str
 48  Q028H         190 non-null    str
 49  Q028I         190 non-null    str
 50  Q028J         190 non-null    str
 51  Q028K         190 non-null    str
 52  Q028L         190 non-null    str
 53  Q028M         190 non-null    str
 54  Q028N         190 non-null    str
 55  Q028O         190 non-null    str
 56  Q028P         190 non-null    str
 57  Q028Q         190 non-null    str
 58  Q028R         190 non-null    str
 59  Q029          263 non-null    str
 60  Q030A         140 non-null    str
 61  Q030B         140 non-null    str
 62  Q030C         140 non-null    str
 63  Q030D         140 non-null    str
 64  Q030E         140 non-null    str
 65  Q030F         140 non-null    str
 66  Q030G         140 non-null    str
 67  Q031          258 non-null    str
 68  Q032A         91 non-null     str
 69  Q032B         91 non-null     str
 70  Q032C         91 non-null     str
 71  Q032D         91 non-null     str
 72  Q032E         91 non-null     str
 73  Q032F         91 non-null     str
 74  Q032G         91 non-null     str
 75  Q033A         91 non-null     str
 76  Q033B         91 non-null     str
 77  Q033C         91 non-null     str
 78  Q033D         91 non-null     str
 79  Q033E         91 non-null     str
 80  Q033F         91 non-null     str
 81  Q033G         91 non-null     str
 82  Q033H         91 non-null     str
 83  Q033I         91 non-null     str
 84  Q033J         91 non-null     str
 85  Q034          258 non-null    str
dtypes: int64(2), str(84)
memory usage: 672.0 KB

In [45]:
df_quest_hab_estudo.isnull().sum()

NU_INSCRICAO      0
TP_RESPOSTA       0
Q001            641
Q002            851
Q003            674
               ...
Q033G           909
Q033H           909
Q033I           909
Q033J           909
Q034            742
Length: 86, dtype: int64

In [50]:
df_quest_hab_estudo.isnull().sum() [df_quest_hab_estudo.isnull().sum() > 0].sort_values(ascending=False)

Q032F    909
Q032E    909
Q032D    909
Q032B    909
Q033J    909
        ...
Q006     698
Q005     694
Q004     688
Q003     674
Q001     641
Length: 84, dtype: int64

### Interpretações

- No dataset de 2022, possuimos uma terceira base com uma pesquisa sobre os hábitos de estudos dos participantes, realizada por conta do período pós-pandemia;
- O principal dataset (`microdados_enem_2022`) permite fazermos junções com a tabela `quest_hab_estudo`, através da coluna `nu_inscrição`;
- O restante das informações seguem a mesma linhagem de estrutura dos demais anos.